// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: restoran.proto

package genprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RestoranServiceClient is the client API for RestoranService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestoranServiceClient interface {
	CreateRestoran(ctx context.Context, in *Restoran, opts ...grpc.CallOption) (*Void, error)
	DeleteRestoran(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
	UpdateRestoran(ctx context.Context, in *Restoran, opts ...grpc.CallOption) (*Void, error)
	GetByIdRestoran(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Restoran, error)
	GetAllRestoran(ctx context.Context, in *Restoran, opts ...grpc.CallOption) (*GetAllRestorans, error)
}

type restoranServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestoranServiceClient(cc grpc.ClientConnInterface) RestoranServiceClient {
	return &restoranServiceClient{cc}
}

func (c *restoranServiceClient) CreateRestoran(ctx context.Context, in *Restoran, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.RestoranService/CreateRestoran", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoranServiceClient) DeleteRestoran(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.RestoranService/DeleteRestoran", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoranServiceClient) UpdateRestoran(ctx context.Context, in *Restoran, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.RestoranService/UpdateRestoran", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoranServiceClient) GetByIdRestoran(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Restoran, error) {
	out := new(Restoran)
	err := c.cc.Invoke(ctx, "/protos.RestoranService/GetByIdRestoran", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restoranServiceClient) GetAllRestoran(ctx context.Context, in *Restoran, opts ...grpc.CallOption) (*GetAllRestorans, error) {
	out := new(GetAllRestorans)
	err := c.cc.Invoke(ctx, "/protos.RestoranService/GetAllRestoran", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestoranServiceServer is the server API for RestoranService service.
// All implementations must embed UnimplementedRestoranServiceServer
// for forward compatibility
type RestoranServiceServer interface {
	CreateRestoran(context.Context, *Restoran) (*Void, error)
	DeleteRestoran(context.Context, *ById) (*Void, error)
	UpdateRestoran(context.Context, *Restoran) (*Void, error)
	GetByIdRestoran(context.Context, *ById) (*Restoran, error)
	GetAllRestoran(context.Context, *Restoran) (*GetAllRestorans, error)
	mustEmbedUnimplementedRestoranServiceServer()
}

// UnimplementedRestoranServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRestoranServiceServer struct {
}

func (UnimplementedRestoranServiceServer) CreateRestoran(context.Context, *Restoran) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestoran not implemented")
}
func (UnimplementedRestoranServiceServer) DeleteRestoran(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRestoran not implemented")
}
func (UnimplementedRestoranServiceServer) UpdateRestoran(context.Context, *Restoran) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestoran not implemented")
}
func (UnimplementedRestoranServiceServer) GetByIdRestoran(context.Context, *ById) (*Restoran, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIdRestoran not implemented")
}
func (UnimplementedRestoranServiceServer) GetAllRestoran(context.Context, *Restoran) (*GetAllRestorans, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRestoran not implemented")
}
func (UnimplementedRestoranServiceServer) mustEmbedUnimplementedRestoranServiceServer() {}

// UnsafeRestoranServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestoranServiceServer will
// result in compilation errors.
type UnsafeRestoranServiceServer interface {
	mustEmbedUnimplementedRestoranServiceServer()
}

func RegisterRestoranServiceServer(s grpc.ServiceRegistrar, srv RestoranServiceServer) {
	s.RegisterService(&RestoranService_ServiceDesc, srv)
}

func _RestoranService_CreateRestoran_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Restoran)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoranServiceServer).CreateRestoran(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RestoranService/CreateRestoran",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoranServiceServer).CreateRestoran(ctx, req.(*Restoran))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoranService_DeleteRestoran_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoranServiceServer).DeleteRestoran(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RestoranService/DeleteRestoran",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoranServiceServer).DeleteRestoran(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoranService_UpdateRestoran_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Restoran)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoranServiceServer).UpdateRestoran(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RestoranService/UpdateRestoran",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoranServiceServer).UpdateRestoran(ctx, req.(*Restoran))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoranService_GetByIdRestoran_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoranServiceServer).GetByIdRestoran(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RestoranService/GetByIdRestoran",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoranServiceServer).GetByIdRestoran(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestoranService_GetAllRestoran_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Restoran)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestoranServiceServer).GetAllRestoran(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.RestoranService/GetAllRestoran",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestoranServiceServer).GetAllRestoran(ctx, req.(*Restoran))
	}
	return interceptor(ctx, in, info, handler)
}

// RestoranService_ServiceDesc is the grpc.ServiceDesc for RestoranService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestoranService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.RestoranService",
	HandlerType: (*RestoranServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRestoran",
			Handler:    _RestoranService_CreateRestoran_Handler,
		},
		{
			MethodName: "DeleteRestoran",
			Handler:    _RestoranService_DeleteRestoran_Handler,
		},
		{
			MethodName: "UpdateRestoran",
			Handler:    _RestoranService_UpdateRestoran_Handler,
		},
		{
			MethodName: "GetByIdRestoran",
			Handler:    _RestoranService_GetByIdRestoran_Handler,
		},
		{
			MethodName: "GetAllRestoran",
			Handler:    _RestoranService_GetAllRestoran_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restoran.proto",
}
